---
- name: Create systemd unit for app
  register: service_unit_added
  notify:
    - Reload daemons
    - Restart systemd unit
  template:
    src: "{{ playbook_dir }}/templates/xxxxxxxxx.j2"
    dest: "/etc/systemd/system/{{ app_name }}.service" # change app_name in vars all to make change in this dest
    owner: root
    group: root
    mode: "0755"

- name: Enable service unit
  when: service_unit_added is changed
  systemd:
    name: {{ app_name }}
    enabled: yes
    daemon_reload: yes
