---
- name: Create systemd unit for app
  register: service_unit_added
  notify:
    - Reload daemons
    - Restart systemd unit
  template:
    src: "{{ playbook_dir }}/templates/my-application.j2"
    dest: "/etc/systemd/system/my-application.service"
    owner: root
    group: root
    mode: "0755"

- name: Enable service unit
  when: service_unit_added is changed
  systemd:
    name: my-application
    enabled: yes

- name: Reload daemons
  systemd:
    daemon_reload: true

- name: Enable service unit
  command: "systemctl restart my-application"