---

- name: "Rust | Ensure shell profiles are clean"
  lineinfile:
    dest: "{{ item[0].stat.path }}"
    regexp: "{{ item[1].regex }}"
    line: "{{ item[1].lineinfile }}"
    state: absent
  with_nested:
  - "{{ stat_shell_profiles.results }}"
  - "{{ shell_exports }}"
  when:
  - shell_profiles is defined
  - shell_exports is defined
  - item[0].stat.exists|bool == true

- name: "Rust | Remove $HOME/.cargo"
  file:
    path: "{{ fubarhouse_user_dir }}/.cargo"
    state: absent
  failed_when: false