---

- name: "Rust | Clone"
  git:
    repo: "https://github.com/rust-lang/rust.git"
    dest: "/tmp/rust"
    version: "{{ rust_version }}"
    clone: yes

- name: "Rust | Build"
  shell: "cd /tmp/rust && ./x.py build"
  changed_when: false

- name: "Rust | Install"
  shell: "cd /tmp/rust && ./x.py install cargo"
  changed_when: false

- name: "Rust | Verify"
  shell: "{{ fubarhouse_user_dir }}/.cargo/bin/rustc --version"
  register: installed_rust_version
  changed_when: false
  failed_when: 'new_rust_version not in installed_rust_version.stdout'