---
# tasks file for ansible-role-amazon-codedeploy

- name: Linux/Unix | Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install CodeDeplot agent
  include_tasks: "setup-{{ ansible_system }}.yml"
