galaxy_info:
  role_name: amazon_codedeploy
  author: diodonfrost
  company: diodonfrost
  description: Ansible role for manage AWS CodeDeploy agent
  license: license Apache

  min_ansible_version: 2.5

  platforms:
    - name: EL
      versions:
        - 8
        - 7
    - name: Fedora
      versions:
        - 29
        - 28
        - 27
        - 26
    - name: Debian
      versions:
        - buster
        - stretch
        - jessie
    - name: Ubuntu
      versions:
        - disco
        - bionic
        - xenial
        - trusty
    - name: Amazon
      versions:
        - 2017.12
        - 2016.03
        - 2013.09

  galaxy_tags:
    - system
    - packaging
    - aws
    - awsagent
    - cloud

dependencies: []
